import assert from 'node:assert/strict';
import { mkdtemp, mkdir, readFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { chromium, expect } from '@playwright/test';
import { createServer } from 'vite';
import type { SceneManifest } from '../src/lib/workspace.ts';

const output = process.env.LAYOUT_EVIDENCE_DIR ?? await mkdtemp(join(tmpdir(), 'layout-evidence-'));
await mkdir(output, { recursive: true });
const web = await createServer({ envFile: false, define: {
  'import.meta.env.VITE_SUPABASE_URL': JSON.stringify(''),
  'import.meta.env.VITE_SUPABASE_ANON_KEY': JSON.stringify(''),
  'import.meta.env.VITE_FORM_GENERATION_ENABLED': JSON.stringify('false'),
}, server: { host: '127.0.0.1', port: 4183, strictPort: true } });
let browser;
try {
  await web.listen();
  browser = await chromium.launch({ headless: true, args: ['--use-angle=swiftshader', '--enable-unsafe-swiftshader'], ...(process.env.ASTRA_CHROME_PATH ? { executablePath: process.env.ASTRA_CHROME_PATH } : {}) });
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
  await context.route('**/*', route => new URL(route.request().url()).hostname === 'fonts.googleapis.com' ? route.fulfill({ contentType: 'text/css', body: '' }) : route.continue());
  const page = await context.newPage();
  const errors: string[] = [];
  page.on('pageerror', e => errors.push(e.message));
  page.on('console', m => { if (m.type() === 'error') errors.push(m.text()); });
  await page.goto('http://127.0.0.1:4183');
  await expect(page).toHaveTitle('Mergence — Spatial Workbench');
  await expect(page.getByRole('button', { name: /Drop files or browse/ })).toBeEnabled();
  await page.getByRole('button', { name: 'New room', exact: true }).click();
  await page.getByRole('dialog', { name: 'Unsaved room changes' }).getByRole('button', { name: 'Discard and continue' }).click();
  const source = { hardware_ir_version: '0.2', overview: { title: 'Layout machine' }, mechanical: { render_dimensions: { x_mm: 1000, y_mm: 2000, z_mm: 3000 } } };
  await page.getByLabel('Import files').setInputFiles({ name: 'machine.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(source)) });
  await expect(page.locator('.asset')).toHaveCount(1);
  const field = (axis: string, kind = 'position') => page.getByLabel(`Layout machine ${axis} ${kind}`, { exact: true });
  const pose = async () => Promise.all(['position', 'rotation'].flatMap(kind => ['X', 'Y', 'Z'].map(axis => field(axis, kind).inputValue().then(Number))));
  const undo = () => page.getByRole('button', { name: 'Undo', exact: true }).click();
  const redo = () => page.getByRole('button', { name: 'Redo', exact: true }).click();
  console.log('Imported fixture');
  await field('X', 'rotation').fill('90');
  await page.getByRole('button', { name: 'Snap to floor', exact: true }).click();
  await expect(page.getByLabel('Layout machine layout measurements')).toContainText('Floor clearance: 0.000 m');
  await expect(field('Y')).toHaveValue('1');
  await undo(); await expect(field('Y')).toHaveValue('0');
  await redo(); await expect(field('Y')).toHaveValue('1');
  await page.getByRole('button', { name: 'Reset position', exact: true }).click();
  await page.locator('.asset').first().click();
  await page.getByRole('button', { name: 'Move', exact: true }).click();
  console.log('Floor and undo passed');
  await page.screenshot({ path: join(output, 'move-controls.png'), timeout: 15000 });
  // Screen coordinates target the visible X arrow in this fixed fixture/viewport.
  // All motion goes through real pointer events, never internal Three/React state.
  const moveHandle = async (cancel: false | 'escape' | 'pointer' = false) => {
    await page.mouse.move(817, 735); await page.mouse.down();
    await page.mouse.move(890, 777, { steps: 8 });
    if (cancel === 'escape') await page.keyboard.press('Escape');
    if (cancel === 'pointer') await page.locator('.viewport canvas').dispatchEvent('pointercancel', { pointerId: 1 });
    await page.mouse.up();
  };
  await page.getByLabel('Drag grid spacing').selectOption('0.5');
  const base = await pose();
  await moveHandle();
  const moved = await pose(); console.log({ base, moved });
  assert.notEqual(moved[0], base[0], 'Pointer drag must change X');
  assert(Math.abs(moved[0] / .5 - Math.round(moved[0] / .5)) < 1e-8);
  assert.deepEqual(moved.slice(1), base.slice(1));
  await undo(); assert.deepEqual(await pose(), base, 'Entire drag is one undo step');
  await redo(); assert.deepEqual(await pose(), moved);
  await undo(); await moveHandle('escape'); assert.deepEqual(await pose(), base, 'Escape cancels the drag');
  await redo(); assert.deepEqual(await pose(), moved, 'Cancelled preview must preserve redo');
  await undo(); await moveHandle('pointer'); assert.deepEqual(await pose(), base, 'Pointer cancellation discards preview');
  await page.getByRole('button', { name: 'Rotate', exact: true }).click();
  await page.screenshot({ path: join(output, 'rotate-controls.png') });
  await page.getByLabel('Keep on floor during drag').check();
  await page.mouse.move(707, 636); await page.mouse.down();
  await page.mouse.move(755, 688, { steps: 10 }); await page.mouse.up();
  const rotated = await pose(); console.log({ rotated });
  assert(rotated.slice(3).some(n => Math.abs(n) > 1), 'Rotation handle must update numeric angles');
  await expect(page.getByLabel('Layout machine layout measurements')).toContainText('Floor clearance: 0.000 m');
  await undo(); assert.deepEqual(await pose(), base);
  await redo(); assert.deepEqual(await pose(), rotated);
  await page.screenshot({ path: join(output, 'rotated-floor.png') });
  await field('X').fill('99');
  await expect(page.getByLabel('Layout machine layout measurements')).toContainText('Extends outside the room bounds.');
  await undo(); assert.deepEqual(await pose(), rotated, 'Numeric editing shares undo history');
  await page.getByRole('button', { name: 'Duplicate', exact: true }).click();
  await expect(page.locator('.asset')).toHaveCount(2);
  await page.getByLabel('Layout machine copy X position', { exact: true }).fill('2.25');
  assert.deepEqual(await pose(), rotated, 'Duplicated instances remain independent');
  await expect(page.getByLabel('Layout machine copy X position', { exact: true })).toHaveValue('2.25');
  await page.locator('.placement').nth(1).getByRole('button', { name: 'Delete instance', exact: true }).click();
  await expect(page.locator('.asset')).toHaveCount(1);
  await undo(); await expect(page.locator('.asset')).toHaveCount(2);
  await expect(page.getByLabel('Layout machine copy X position', { exact: true })).toHaveValue('2.25');
  const download = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Export scene JSON', exact: true }).click();
  const exportedPath = join(output, 'layout.json'); await (await download).saveAs(exportedPath);
  const exported: SceneManifest = JSON.parse(await readFile(exportedPath, 'utf8'));
  assert.equal(exported.bundledAssets!.length, 1, 'Instances share their source asset');
  assert.deepEqual(exported.instances[0].position, rotated.slice(0, 3));
  assert.deepEqual(exported.instances[0].rotation, rotated.slice(3));
  assert.equal(exported.instances[1].assetId, exported.instances[0].assetId);
  assert.deepEqual(exported.bundledAssets![0].formProject!.ir, source);
  await expect(page.getByRole('status', { name: 'Local draft status' })).toHaveText('Local draft saved');
  await page.reload(); await expect(page.locator('.asset')).toHaveCount(2);
  assert.deepEqual(await pose(), rotated, 'Committed transform survives reload');
  await page.locator('.asset').first().click();
  await page.getByRole('button', { name: 'Play animation', exact: true }).click();
  await page.getByRole('button', { name: 'Move', exact: true }).click();
  await expect(page.locator('.timeline')).toContainText('Base layout');
  await expect(page.getByRole('button', { name: 'Play animation', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Enter fullscreen', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Exit fullscreen', exact: true })).toBeVisible();
  await page.screenshot({ path: join(output, 'fullscreen.png') });
  await page.getByRole('button', { name: 'Exit fullscreen', exact: true }).click();
  await page.setViewportSize({ width: 390, height: 844 }); await page.evaluate(() => window.scrollTo(0, 0));
  await expect(page.getByRole('region', { name: 'Layout tools' })).toBeVisible();
  await page.getByRole('button', { name: 'Rotate', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Rotate', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await page.screenshot({ path: join(output, 'mobile.png') });
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), 'No horizontal mobile overflow');
  await expect(page.locator('vite-error-overlay')).toHaveCount(0);
  assert.deepEqual(errors, []);
  console.log(`Layout browser checks passed. Evidence: ${output}`);
} finally { await browser?.close(); await web.close(); }
